import Head from "next/head";
// import Image from "next/image";
import Header from "../components/Header";
import Slider from "../components/Slider";
import Container from "../components/Container";
// import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dan's Group | Home</title>
      </Head>
      <Header />
      <Slider />
      <Container>
        <div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
          <div>Custom content Loading...</div>
        </div>
      </Container>
    </>
  );
}
